@localhost = http://localhost:3000
@heroku = https://evening-tor-08768.herokuapp.com

@url = {{localhost}}


### Get all resources
GET {{url}}/api/resources HTTP/1.1

### Get Types
GET {{url}}/api/resources/types HTTP/1.1

### Get Types by ID
GET {{url}}/api/resources/types/1 HTTP/1.1

### Get Attributes by type
GET {{url}}/api/resources/Water/attributes HTTP/1.1

### Get Available resources optional 
GET {{url}}/api/resources/available HTTP/1.1

### Get requests by id and keyword
GET {{url}}/api/resources/2 HTTP/1.1

### Get all purchases
GET {{url}}/api/resources/purchase HTTP/1.1

### Get purchases by id
GET {{url}}/api/resources/purchase/3 HTTP/1.1

### Get suppliers
GET {{url}}/api/resources HTTP/1.1
