@localhost = http://localhost:3000
@heroku = https://evening-tor-08768.herokuapp.com

@url = {{localhost}}


### Get all resources
GET {{url}}/api/resources HTTP/1.1

### Get Types
GET {{url}}/api/resources/types HTTP/1.1

### Get Types by ID
GET {{url}}/api/resources/types/1 HTTP/1.1

### Get Attributes by type
GET {{url}}/api/resources/Baby%20Food/attributes HTTP/1.1

###
GET {{url}}/api/resources/available/2

### Get Available resources 
GET {{url}}/api/resources/available HTTP/1.1

### Get Available resources of supplier 2
GET {{url}}/api/resources/available/2 HTTP/1.1

### Get Available resources searched by keyword 
GET {{url}}/api/resources/available?keyword=a HTTP/1.1

### Get Available resources searched by id=3, id supperceds keyword 
GET {{url}}/api/resources/available/3?keyword=baBy HTTP/1.1

### Get requests by id and keyword
GET {{url}}/api/resources/2 HTTP/1.1

### Get all purchases
GET {{url}}/api/resources/purchase HTTP/1.1

### Get purchases by id
GET {{url}}/api/resources/purchase/1 HTTP/1.1
###
GET {{url}}/api/resources/purchase/2 HTTP/1.1

### Get suppliers
GET {{url}}/api/resources HTTP/1.1

###

GET {{url}}/api/resources/requests

###

GET {{url}}/api/resources/requests/3

###

GET {{url}}/api/resources/requests?keyword=

###

GET {{url}}/api/resources/requests/1?keyword=wA

###
GET {{url}}/api/resources/purchases

###
GET {{url}}/api/resources/purchases/1

###
GET {{url}}/api/resources/purchases/2


###
GET {{url}}/api/resources/reserves

###
GET {{url}}/api/resources/reserves/2