@localhost = http://localhost:3000
@heroku = https://evening-tor-08768.herokuapp.com

@url = {{localhost}}

###

GET {{url}}/api/users/roles

###

GET {{url}}/api/users

###

GET {{url}}/api/users?debug=true

###

GET {{url}}/api/users/2

###

GET {{url}}/api/users/2?debug=true

###

GET {{url}}/api/users/2?enabled=false&debug=true

###

GET {{url}}/api/users/2?enabled=true&debug=false

###

GET {{url}}/api/users/administrators

###

GET {{url}}/api/users/administrators?debug=true

###

GET {{url}}/api/users/2/requests

###

GET {{url}}/api/users/3/reserves

###

GET {{url}}/api/users/2/purchases
