@localhost = http://localhost:3000
@heroku = https://evening-tor-08768.herokuapp.com

@url = {{localhost}}

###

POST {{url}}/api/users/administrator HTTP/1.1
content-type: application/json

{
    "username": "gabrielTe1",
    "password": "12345678",
    "first_name": "Gabriel",
    "last_name": "Santiago",
    "email": "thisia.test@upr.edu",
    "address": {
        "street1": "Calle ",
        "city": "Cabo Rojo",
        "zip_code": "00645",
        "country": "Puerto Rico"
    },
    "gender":"Male",
    "dob": "1998-12-09",
    "phone_number": "7879221444"
}

###
