@localhost = http://localhost:3000
@heroku = https://evening-tor-08768.herokuapp.com

@url = {{localhost}}

### invalid user role, this is admin
POST {{url}}/api/suppliers/organizations HTTP/1.1
content-type: application/json

{
    "userid":"1",
    "organization_name": "Habitat 4 Humanity",
    "address": {
        "street1": "23 Hudson Ave.",
        "city": "Luquillo",
        "zip_code":"00865",
        "country": "Puerto Rico"
    },
    "phone_number": "8983741009",
    "email": "organization@habitat.humanity"
}

### invalid user role, this is admin
POST {{url}}/api/suppliers/organizations HTTP/1.1
content-type: application/json

{
    "userid":"9",
    "organization_name": "Habitat 4 Humanity",
    "address": {
        "street1": "23 Hudson Ave.",
        "city": "Luquillo",
        "zip_code":"00865",
        "country": "Puerto Rico"
    },
    "phone_number": "8983741009",
    "email": "organization@habitat.humanity"
}

### bad role
POST {{url}}/api/suppliers/organizations/1/representative HTTP/1.1
content-type: application/json

{
    "representative_id":"5",
    "adminid":10
}

### bad role: rep to add is not supplier
POST {{url}}/api/suppliers/organizations/1/representative HTTP/1.1
content-type: application/json

{
    "representative_id":"6",
    "adminid":2
}



### good
POST {{url}}/api/suppliers/organizations/1/representative HTTP/1.1
content-type: application/json

{
    "representative_id":"5",
    "adminid":2
}
